services:
  matrix-musicbot:
    image: ghcr.io/sultanalburaq/matrix-element-call-musicbot:latest
    container_name: matrix-musicbot
    restart: unless-stopped
    environment:
      - CONFIG_FILE=/app/config/config.toml
    volumes:
      - ./config:/app/config:ro
      - ./logs:/app/logs
      - ./data:/app/data
      - ./cache:/tmp/musicbot_audio
    network_mode: host
    logging:
      driver: json-file
      options:
        max-size: "20m"
        max-file: "3"
